<?xml version="1.0" encoding="UTF-8"?>
<!--
  Default template invoked by Berlioz for JSON output

  The XML generated by this template should map to a simple JSON tree model
  following the Aeson format.

  @see https://www.pageseeder.org/projects/aeson/format.html
-->
<xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:json="http://pageseeder.org/JSON"
                exclude-result-prefixes="#all">

<!-- JSON output properties -->
<xsl:output method="xml" media-type="application/json" encoding="utf-8"/>

<!-- Default -->
<xsl:template match="/root">
<json:object/>
</xsl:template>

</xsl:stylesheet>
